<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="base_width" value="0.62265" />
	<xacro:property name="base_height" value="0.37817" />
	<xacro:property name="base_mass" value="8.20" />
	
	<xacro:macro name="base" params="name">
	
		<link name="${name}_link">
		  <visual>
			<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
			<geometry>
			  <box size="${base_width} ${base_width} ${base_height}" />
			</geometry>
			<material name="white"/>
		  </visual>
		  <collision>
			<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
			<geometry>
			  <box size="${base_width} ${base_width} ${base_height}" />
			</geometry>
		  </collision>
		  <xacro:inertial_template mass="${base_mass}" length="${base_width}" width="${base_width}" height="${base_height}"/>
		</link>
		
	</xacro:macro>

</robot>
